alter table public.noticias
  add column if not exists fonte_nome text,
  add column if not exists fonte_url text;

create unique index if not exists noticias_fonte_url_key
  on public.noticias (fonte_url)
  where fonte_url is not null;

create table if not exists public.noticias_pendentes (
  id bigint generated by default as identity primary key,
  titulo text not null,
  resumo text not null default '',
  conteudo text not null default '',
  categoria text not null default 'Região',
  data date not null default current_date,
  imagem text,
  autor text not null,
  fonte_nome text not null,
  fonte_url text not null unique,
  status text not null default 'pendente' check (status in ('pendente', 'publicada', 'descartada')),
  created_at timestamptz not null default now()
);

alter table public.noticias_pendentes enable row level security;

grant select, update on table public.noticias_pendentes to authenticated;
grant usage, select on sequence public.noticias_pendentes_id_seq to authenticated;

drop policy if exists "Admins podem ver sugestoes" on public.noticias_pendentes;
create policy "Admins podem ver sugestoes"
on public.noticias_pendentes for select
to authenticated
using (exists (
  select 1 from public.admin_users
  where admin_users.user_id = (select auth.uid())
));

drop policy if exists "Admins podem atualizar sugestoes" on public.noticias_pendentes;
create policy "Admins podem atualizar sugestoes"
on public.noticias_pendentes for update
to authenticated
using (exists (
  select 1 from public.admin_users
  where admin_users.user_id = (select auth.uid())
))
with check (exists (
  select 1 from public.admin_users
  where admin_users.user_id = (select auth.uid())
));
